env:
  EXPIRY_DAYS: "1"
  RUST_LOG: info
  SQLITE_URI: sqlite:///persist/rustpad_db.db
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rustpad
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  storagedatabase:
    enabled: true
    mountPath: /persist
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 3030
        protocol: TCP
        targetPort: 3030
