image:
  repository: tccr.io/truecharts/tautulli
  pullPolicy: IfNotPresent
  tag: 2.11.0@sha256:0d942a6c0dcacdbc46dbde6eae27132530b1274fc0c79f5c1e0f9bfed43ec010

service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
