image:
  repository: tccr.io/truecharts/tautulli
  pullPolicy: IfNotPresent
  tag: 2.10.5@sha256:3d2539aa3cb28df16699c91e2aa8a7a9c93230e8d43b5d50e3359d01d4b5aa5c

service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
