env:
  ADD: shiny
  PASSWORD: yourpasswordhere
  ROOT: "FALSE"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rstudio
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  userdatadirectory:
    enabled: true
    mountPath: /home/rstudio/Documents
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  hostport2:
    enabled: true
    ports:
      hostport2:
        enabled: true
        port: 3838
        protocol: TCP
        targetPort: 3838
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8787
        protocol: HTTP
        targetPort: 8787
