# Fake external service image
image:
  repository: tccr.io/truecharts/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:666

# Disable Deployment
controller:
  enabled: false

service:
  main:
    type: ExternalIP
    externalIP: "1.1.1.1"
    ports:
      main:
        Type: HTTPS
        port: 10003
        targetPort: 443

portal:
  enabled: true
