# Default values for Organizr.

image:
  repository: organizr/organizr
  pullPolicy: Always
  tag: latest

strategy:
  type: Recreate

# Configure the Security Context for the Pod
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

service:
  main:
    ports:
      main:
        port: 80

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir:
      enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
