env:
  GAME_ID: "600760"
  GAME_PARAMS: AutoSave true SaveInterval 300
  PASSWRD: ""
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/stationeers
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  gameport:
    enabled: true
    ports:
      gameport:
        enabled: true
        port: 27500
        protocol: UDP
        targetPort: 27500
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 27015
        protocol: UDP
        targetPort: 27015
