env:
  DATA_PERM: "770"
  DL_URL: http://files.star-made.org/StarMade-Starter.jar
  GAME_PARAMS: ""
  RUNTIME_NAME: basicjre
  STARTER_PARAMS: -nogui
  UMASK: "000"
  XMS_SIZE: "1024"
  XMX_SIZE: "1024"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/starmade
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /starmade
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 4242
        protocol: TCP
        targetPort: 4242
