env:
  GAME_ID: "443030"
  GAME_PARAMS: ""
  PASSWRD: ""
  USERNAME: ""
  VALIDATE: ""
  WS_CONTENT: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/conanexiles
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  gameport1:
    enabled: true
    ports:
      gameport1:
        enabled: true
        port: 7778
        protocol: UDP
        targetPort: 7778
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 7777
        protocol: UDP
        targetPort: 7777
  steamport:
    enabled: true
    ports:
      steamport:
        enabled: true
        port: 27015
        protocol: UDP
        targetPort: 27015
