env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pixelserv-tls
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  certficatesdir:
    enabled: true
    mountPath: /var/cache/pixelserv
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  http:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
        protocol: TCP
        targetPort: 80
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 443
        protocol: HTTP
        targetPort: 443
