env:
  CAVES: "true"
  FORCE_X64: "true"
  GAME_ID: "343050"
  PASSWRD: ""
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/dontstarvetogether
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
  token:
    enabled: true
    mountPath: /serverdata/.klei/DoNotStarveTogether
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  authentication:
    enabled: true
    ports:
      authentication:
        enabled: true
        port: 8766
        protocol: UDP
        targetPort: 8766
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 10890
        protocol: UDP
        targetPort: 10890
  masterserver:
    enabled: true
    ports:
      masterserver:
        enabled: true
        port: 27016
        protocol: UDP
        targetPort: 27016
