env:
  DL_URL_PATCH: https://ftp.gwdg.de/pub/misc/ftp.idsoftware.com/idstuff/quake3/quake3-1.32c.zip
  DL_URL_PR: https://ftp.gwdg.de/pub/misc/ftp.idsoftware.com/idstuff/quake3/linux/linuxq3apoint-1.32b-3.x86.run
  GAME_PARAMS: +set sv_punkbuster 0 +set fs_game osp +set com_hunkMegs 32
  Q3_MAP: q3dm1
  Q3_PORT: "27960"
  UMASK: "000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/quake3
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /quake3
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 27960
        protocol: UDP
        targetPort: 27960
