image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/zoneminder
  tag: latest@sha256:bb6b2c4d7b8e2d3fbd6f4fe25c1ce7729813505b7544f02308aa64d6d78039fd

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 10292
        protocol: HTTPS
        targetPort: 443
  zmninja:
    enabled: true
    ports:
      zmninja:
        enabled: true
        port: 10293
        protocol: TCP
        targetPort: 9000

probes:
  liveness:
    path: "/zm"
  readiness:
    path: "/zm"
  startup:
    path: "/zm"

persistence:
  config:
    enabled: true
    mountPath: /config
  datapath:
    enabled: true
    mountPath: /var/cache/zoneminder

portal:
  enabled: true
