env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/plexripper
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
  downloadfolder:
    enabled: true
    mountPath: /downloads
  moviedestinationfolder:
    enabled: true
    mountPath: /movies
  tv-showdestinationfolder:
    enabled: true
    mountPath: /tvshows
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 7000
        protocol: TCP
        targetPort: 7000
