env:
  ANONYMOUS_METHODS: ""
  AUTH_TYPE: Basic
  LOCATION: /
  PASSWORD: ""
  PUMASK: "0000"
  REALM: WebDAV-Login
  SERVER_NAMES: localhost
  SSL_CERT: ""
  USERNAME: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/apache-webdav
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /var/lib/dav
  data:
    enabled: true
    mountPath: /var/lib/dav/data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8384
        protocol: TCP
        targetPort: 80
