env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/kdenlive-vnc
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  content:
    enabled: true
    mountPath: /sharedContent
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 5800
        protocol: HTTP
        targetPort: 5800
  vncport:
    enabled: true
    ports:
      vncport:
        enabled: true
        port: 5900
        protocol: TCP
        targetPort: 5900
