env:
  CUSTOMER_KEY: pwHB3mLCOUWscFi7
  GAME_ID: "920720"
  GAME_PARAMS: -port=5555 -QueryPort=27015 -NoLiveServer -EnableCheats
  IDENTIFIER: dockeroasis
  PASSWRD: ""
  PROVIDER_KEY: " 8IhohaMRZIJJubv5 "
  SLOTS: "20"
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/lastoasis
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 5555
        protocol: UDP
        targetPort: 5555
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 27015
        protocol: UDP
        targetPort: 27015
