env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/damselfly
  tag: latest@sha256:029332f60c5b3cc54ec1b1bd2151dc9a043a7aaa4ea8d435694c25801237fa4d
persistence:
  config:
    enabled: true
    mountPath: /config
  pictures:
    enabled: true
    mountPath: /pictures
  thumbs:
    enabled: true
    mountPath: /thumbs
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 6363
        protocol: TCP
        targetPort: 6363

portal:
  enabled: true
