env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/damselfly
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
  pictures:
    enabled: true
    mountPath: /pictures
  thumbs:
    enabled: true
    mountPath: /thumbs
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 6363
        protocol: TCP
        targetPort: 6363
