env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/crypto-exchanges-gateway
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  configpath:
    enabled: true
    mountPath: /root/crypto-exchanges-gateway/custom_config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8000
        protocol: HTTP
        targetPort: 8000
  wsport:
    enabled: true
    ports:
      wsport:
        enabled: true
        port: 8001
        protocol: TCP
        targetPort: 8001
