owner: truecharts
git-repo: apps
repo: apps
charts-dir: charts/*
charts_repo_url: "https://charts.truecharts.org"
excluded-charts: common-test
pages-branch: "gh-pages"
SkipExisting: true
skipExisting: true
