owner: truecharts
git-repo: charts
repo: charts
charts-dir: charts/*
charts_repo_url: "https://charts.truecharts.org"
excluded-charts: common-test
pages-branch: "master"
SkipExisting: true
skipExisting: true
index-path: "chartsrepo/index.yaml"
