# Default values for grocy.

image:
  repository: linuxserver/grocy
  tag: version-v2.7.1
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

# Configure the Security Context for the Pod
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

service:
  main:
    ports:
      main:
        port: 80

env: {}
  # TZ:
  # PUID:
  # PGID:

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir:
      enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
