env:
  DOWNLOAD: http://download.kiwix.org/zim/wikipedia_en_chemistry_nopic.zim
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/kiwix-serve
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  data:
    enabled: true
    mountPath: /data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8040
        protocol: TCP
        targetPort: 80
