env:
  SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/sonarqube
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  data:
    enabled: true
    mountPath: /opt/sonarqube/data
  extensions:
    enabled: true
    mountPath: /opt/sonarqube/extensions
  logs:
    enabled: true
    mountPath: /opt/sonarqube/logs
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 9000
        protocol: TCP
        targetPort: 9000
