image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: 0.20.2273@sha256:e25d0b7ef90c709ef89f96388b29cdb76fb7ac10d7d9b6e7c11f7cb182c2a490

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 9117
        port: 9117

probes:
  liveness:
    path: "/UI/Login"

  readiness:
    path: "/UI/Login"

  startup:
    path: "/UI/Login"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
