image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: 0.20.2255@sha256:b53e0e2a41a88f51991a8ef7552920a5e9a57dae425c420ddbeba488e6225b4d

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 9117
        port: 9117

probes:
  liveness:
    path: "/UI/Login"

  readiness:
    path: "/UI/Login"

  startup:
    path: "/UI/Login"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
