env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/dvblink
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  dvblink:
    enabled: true
    mountPath: /opt/DVBLink
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 39876
        protocol: HTTP
        targetPort: 39876
  tcpport1:
    enabled: true
    ports:
      tcpport1:
        enabled: true
        port: 8100
        protocol: TCP
        targetPort: 8100
  tcpport2:
    enabled: true
    ports:
      tcpport2:
        enabled: true
        port: 2222
        protocol: TCP
        targetPort: 22
