env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/auto-yt-dl
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  data:
    enabled: true
    mountPath: /app/data
  hostpath1:
    enabled: true
    mountPath: /app/Downloads
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 5000
        protocol: TCP
        targetPort: 5000
