env:
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pyload-ng
  tag: latest@sha256:d7526c19d6d0c502944693b4c7c33c9bd9a9de2c5dc32a7f925a84a3d0f04adc
persistence:
  config:
    enabled: true
    mountPath: /config
  pathdownloads:
    enabled: true
    mountPath: /downloads
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8000
        protocol: HTTP
        targetPort: 8000
  port9666:
    enabled: true
    ports:
      port9666:
        enabled: true
        port: 9666
        protocol: TCP
        targetPort: 9666

portal:
  enabled: true
