env:
  YOURLS_DB_HOST: ""
  YOURLS_DB_NAME: ""
  YOURLS_DB_PASS: ""
  YOURLS_HOURS_OFFSET: ""
  YOURLS_PASS: ""
  YOURLS_PRIVATE: ""
  YOURLS_SITE: ""
  YOURLS_USER: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/yourls
  tag: latest@sha256:7cec4323197810e817ac53934cfb421efd4dd387fae7c528615fd1c2ae0bb992
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 80
        protocol: TCP
        targetPort: 80

portal:
  enabled: true
