image:
  repository: tccr.io/truecharts/sabnzbd
  pullPolicy: IfNotPresent
  tag: 3.7.0@sha256:fab92cd5cdf4ad311ecd280b7bef27e25a74c7ff2327e58a879164bc4e9e75ac

env:
  HOST_WHITELIST_ENTRIES: ""

service:
  main:
    ports:
      main:
        port: 10097
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
