env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/youtransfer
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /opt/youtransfer/config
  hostpath3:
    enabled: true
    mountPath: /opt/youtransfer/uploads
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 5000
        protocol: TCP
        targetPort: 5000
