image:
  repository: tccr.io/truecharts/ombi
  pullPolicy: IfNotPresent
  tag: 4.35.1@sha256:1fd10405056ff77b8e50716b3556a47b5d2e8648e3e070b71e1317ef8872b720

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 3579
        targetPort: 3579

persistence:
  config:
    enabled: true
    mountPath: "/config"

# Enabled mariadb
# ... for more options see https://github.com/tccr.io/truecharts/charts/tree/master/tccr.io/truecharts/mariadb
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: ombi
    username: ombi
    password: ombi
  primary:
    persistence:
      enabled: false

portal:
  enabled: true
