env:
  DATA_PERM: "770"
  GAME_ID: "746200"
  GAME_PARAMS: Port=10027 QueryPort=10037 -log
  PASSWRD: ""
  UMASK: "000"
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/postscriptum
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 10027
        protocol: UDP
        targetPort: 10027
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 10037
        protocol: UDP
        targetPort: 10037
