env:
  GOKAPI_LENGTH_ID: "10"
  GOKAPI_MAX_FILESIZE: "5"
  GOKAPI_PASSWORD: unraid
  GOKAPI_USERNAME: unraid
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/gokapi
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /app/config
  data:
    enabled: true
    mountPath: /app/data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 53842
        protocol: TCP
        targetPort: 53842
