image:
  repository: tccr.io/truecharts/pingvin-share
  pullPolicy: IfNotPresent
  tag: 0.5.1@sha256:74d6ae35ecf82c107e62f5eb6ecb7dc4a3a9a670202e1486eece497486d35af9

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10595

persistence:
  data:
    enabled: true
    mountPath: /opt/app/backend/data

portal:
  enabled: true
