image:
  repository: tccr.io/truecharts/pingvin-share
  pullPolicy: IfNotPresent
  tag: 0.3.4@sha256:34e1c4630cbca311efe08800866746d5183717783857c93e69176ca1108cdfcf

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10595

persistence:
  data:
    enabled: true
    mountPath: /opt/app/backend/data

portal:
  enabled: true
