env:
  GAME_ID: "897590"
  GAME_PARAMS: ""
  MULTIHOME: ""
  PASSWRD: ""
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/memories-of-mars
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  beaconport:
    enabled: true
    ports:
      beaconport:
        enabled: true
        port: 15000
        protocol: UDP
        targetPort: 15000
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 7777
        protocol: UDP
        targetPort: 7777
