env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/trango
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  hostport2:
    enabled: true
    ports:
      hostport2:
        enabled: true
        port: 5533
        protocol: TCP
        targetPort: 443
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 7755
        protocol: TCP
        targetPort: 80
