env:
  API_SECRET: ""
  BASE_URL: ""
  BG_HIGH: ""
  BG_LOW: ""
  BG_TARGET_BOTTOM: ""
  BG_TARGET_TOP: ""
  DISPLAY_UNITS: ""
  ENABLE: delta direction upbat timeago devicestatus errorcodes ar2 simplealarms profile
  INSECURE_USE_HTTP: "true"
  MONGO_CONNECTION: mongodb://db-user:db-password@mongodb-instance:port/db-name
  THEME: colors
  TIME_FORMAT: "24"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/nightscout
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 1337
        protocol: TCP
        targetPort: 1337
