env:
  name: monerod
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/monero-node
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  blockchainstorage:
    enabled: true
    mountPath: /home/monero/.bitmonero
  containerdir1:
    enabled: true
    mountPath: /usr/local
  containerdir2:
    enabled: true
    mountPath: /src
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 18080
        protocol: TCP
        targetPort: 18080
  port2:
    enabled: true
    ports:
      port2:
        enabled: true
        port: 18081
        protocol: TCP
        targetPort: 18081
