image:
  repository: tccr.io/truecharts/libremdb
  pullPolicy: IfNotPresent
  tag: latest@sha256:5a3b84d979c36018a4f75e69786a531fd7ceae3a3be378ce54d0ef64e8b15fdf

env:
  NEXT_PUBLIC_URL: http://localhost:3000
  NEXT_TELEMETRY_DISABLED: 1
  AXIOS_USERAGENT: "axios/0.27.2"
  AXIOS_ACCEPT: "application/json, text/plain, */*"
  AXIOS_LANGUAGE: "en-US,en;q=0.5"
  USE_REDIS: true
  REDIS_URL:
    secretKeyRef:
      name: rediscreds
      key: url

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10593

persistence:
  config:
    enabled: true
    mountPath: /opt/app

redis:
  enabled: true
  existingSecret: rediscreds

portal:
  enabled: true
