env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/bitcoind
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  data:
    enabled: true
    mountPath: /root/.bitcoin/
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  localrpc:
    enabled: true
    ports:
      localrpc:
        enabled: true
        port: 8332
        protocol: TCP
        targetPort: 8332
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8333
        protocol: TCP
        targetPort: 8333
