env:
  CUSTOM_RES_H: "768"
  CUSTOM_RES_W: "1280"
  NOVNC_RESIZE: remote
  RUNASROOT: "false"
  USER_LOCALES: en_US.UTF-8 UTF-8
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/krusader
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  containerpath:
    enabled: true
    mountPath: /krusader
  datapath:
    enabled: true
    mountPath: /mnt/user
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8080
        protocol: TCP
        targetPort: 8080
