env:
  CUSTOM_RES_H: "1000"
  CUSTOM_RES_W: "1800"
  DATA_PERM: "770"
  DEV: ""
  ROOT_PWD: ""
  UMASK: "0000"
  USER_LOCALES: en_US.UTF-8 UTF-8
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/debian-bullseye
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  homedirectory:
    enabled: true
    mountPath: /debian
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8080
        protocol: TCP
        targetPort: 8080
