env:
  AquireRomSets: ""
  AutoStart: ""
  ConcurrentDownloadThreads: ""
  DeDupe: ""
  EnableUnsupportedPlatforms: ""
  ScrapeMetadata: ""
  ScreenscraperPassword: ""
  ScreenscraperUsername: ""
  ScriptInterval: ""
  keepBackupsOfImportedRoms: ""
  skyscraperLanguagePreference: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ra-rom-processor
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
  hostpathforbackup:
    enabled: true
    mountPath: /backup
  hostpathforcache:
    enabled: true
    mountPath: /cache
  hostpathforinput:
    enabled: true
    mountPath: /input
  hostpathforoutput:
    enabled: true
    mountPath: /output
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
