image:
  repository: tccr.io/truecharts/storj-node
  tag: 1.68.1@sha256:9f13b0b5f3cb49114161036c5d1e118f9d39660af6feda2de954ee2f7f1b4af7
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  WALLET: "walletaddress"

env:
  SETUP: true
  EMAIL: ""
  ADDRESS: ""
  STORAGE: "500GB"

service:
  main:
    ports:
      main:
        port: 14002
        targetPort: 14002
  coretcp:
    enabled: true
    ports:
      coretcp:
        enabled: true
        protocol: TCP
        port: 28967
        targetPort: 28967
  coreudp:
    enabled: true
    ports:
      coreudp:
        enabled: true
        protocol: UDP
        port: 28967
        targetPort: 28967

persistence:
  identity:
    enabled: true
    mountPath: "/app/identity"
  storage:
    enabled: true
    mountPath: "/app/config"

portal:
  enabled: true
