env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/mailpile
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  path1:
    enabled: true
    mountPath: /root/.local/share/Mailpile
  path2:
    enabled: true
    mountPath: /root/.gnupg
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 33411
        protocol: TCP
        targetPort: 33411
