image:
  repository: tccr.io/truecharts/openspeedtest
  pullPolicy: IfNotPresent
  tag: latest@sha256:f88aa7ec3ee4fa3eff5e61fd7631be5e93d8db52daecfe40bba6ccf231f20bcf

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10256

portal:
  enabled: true
