env:
  DATA_PATH: ""
  GAME_ID: examplegameidwillgohere
  MAX_PLAYERS: "10"
  WORLD_INDEX: "0"
  WORLD_NAME: World name here
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/core-keeper-dedicated-server
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  datafiles:
    enabled: true
    mountPath: /home/steam/core-keeper-data
  serverfiles:
    enabled: true
    mountPath: /home/steam/core-keeper-dedicated
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
