env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/observium
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  observium:
    enabled: true
    mountPath: /opt/observium/rrd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8668
        protocol: HTTP
        targetPort: 8668
  udpport1:
    enabled: true
    ports:
      udpport1:
        enabled: true
        port: 8514
        protocol: UDP
        targetPort: 514
