# Default values for Unifi.

image:
  repository: jacobalberty/unifi
  tag: 6.1.71
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

# Configure the Security Context for the Pod
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

envTpl:
# Permissions Settings
  UNIFI_GID: "568"
  UNIFI_UID: "568"

service:
  main:
    ports:
      main:
        port: 8443
  conn:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 8080
        protocol: TCP
      stun:
        enabled: true
        port: 3478
        protocol: UDP

env: {}
  # TZ:
  # PUID:
  # PGID:

persistence:
  config:
    enabled: true
    mountPath: "/unifi"
    emptyDir:
      enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
