env:
  BASIC_AUTH: "True"
  BASIC_AUTH_PASSWORD: x
  BASIC_AUTH_USERNAME: x
  DEBUG: "False"
  EXCLUDE_IPS: ""
  SKIP_ARCHIVED_LOGS: "False"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/goaccess-npm-logs
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  hostpath1:
    enabled: true
    mountPath: /opt/log
    readOnly: true
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 7880
        protocol: TCP
        targetPort: 7880
