env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/crafty-3
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  backups:
    enabled: true
    mountPath: /crafty_web/backups
  database:
    enabled: true
    mountPath: /crafty_db
  server-files:
    enabled: true
    mountPath: /minecraft_servers
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 1800
        protocol: HTTP
        targetPort: 8000
  minecraftports:
    enabled: true
    ports:
      minecraftports:
        enabled: true
        port: 25500
        protocol: TCP
        targetPort: 25500
