image:
  repository: tccr.io/truecharts/flexget
  pullPolicy: IfNotPresent
  tag: 3.5.15@sha256:adfe1737cb3e6656acc3710bd58c6c8a7b00bdef8f86d19e3f098d0ed7414450

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10174
        targetPort: 5050

env:
  FG_LOG_LEVEL: info
  FG_LOG_FILE: flexget.log

secretEnv:
  FG_WEBUI_PASSWD: "jLeT78KBDPW"

persistence:
  config:
    enabled: true
    mountPath: "/config"

  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
