image:
  repository: tccr.io/truecharts/jdownloader-2
  pullPolicy: IfNotPresent
  tag: 22.11.2@sha256:d421fefe647fb6bf68b31caf72e54099ebfb8905f2b08d594238e3b994fc0830

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10054
        targetPort: 5800
  myjd:
    enabled: true
    ports:
      myjd:
        enabled: true
        port: 3129
        targetPort: 3129
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10056
        targetPort: 5900

envFrom:
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-jdownloader'

secretEnv:
  VNC_PASSWORD: ""

jdownloader:
  # General Settings
  KEEP_APP_RUNNING: false
  # GUI Settings
  DISPLAY_WIDTH: 1280
  DISPLAY_HEIGHT: 768
  SECURE_CONNECTION: false
  ENABLE_CJK_FONT: false

configmap:
  jdownloader:
    enabled: true
    data:
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.jdownloader.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.jdownloader.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.jdownloader.SECURE_CONNECTION }}'
      DISPLAY_WIDTH: "{{ .Values.jdownloader.DISPLAY_WIDTH }}"
      DISPLAY_HEIGHT: "{{ .Values.jdownloader.DISPLAY_HEIGHT }}"

persistence:
  config:
    enabled: true
    mountPath: "/config"
  output:
    enabled: true
    mountPath: "/output"

portal:
  enabled: true
