env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tachidesk-docker
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  appdata:
    enabled: true
    mountPath: /home/suwayomi/.local/share/Tachidesk
  library:
    enabled: true
    mountPath: /home/suwayomi/.local/share/Tachidesk/downloads
  local-library:
    enabled: true
    mountPath: /home/suwayomi/.local/share/Tachidesk/local
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 4567
        protocol: TCP
        targetPort: 4567
