env:
  BEAMDURATION: "0"
  DISARMCODE: ""
  ENABLECAMERAS: "false"
  ENABLEMODES: "false"
  ENABLEPANIC: "false"
  MQTTHOST: ""
  MQTTPASSWORD: ""
  MQTTPORT: "1883"
  MQTTUSER: ""
  RINGLOCATIONIDS: ""
  RINGTOKEN: ""
  SNAPSHOTMODE: disabled
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ring-mqtt
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  data:
    enabled: true
    mountPath: /data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
