env:
  DISPLAY_HEIGHT: 800|900|1050
  DISPLAY_WIDTH: 1440|1680
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/btdex
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  btdex:
    enabled: true
    mountPath: /opt/btdex/cache
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 5800
        protocol: TCP
        targetPort: 8080
