image:
  repository: tccr.io/truecharts/ddns-go
  pullPolicy: IfNotPresent
  tag: 4.5.1@sha256:f0cd7e897810f7f389b63b32947effe196738e90f4f2bf01433c05da514e0ff4

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 9876
        port: 10168

persistence:
  data:
    enabled: true
    mountPath: "/root"

portal:
  enabled: true
