env:
  ADDRESS: 0.0.0.0
  FORCE_WEBP: "0"
  IMGUR_CLIENT_ID: 546c25a59c58ad7
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rimgo
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 3000
        protocol: TCP
        targetPort: 3000
