image:
  repository: tccr.io/truecharts/grocy
  tag: v3.1.3@sha256:08b7c1bfdd0df8a2ef6a87bb043afcd6502d58070d5690b4ec620478bff2c0af
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80

env: {}
  # TZ:
  # PUID:

persistence:
  config:
    enabled: true
    mountPath: "/config"
