env:
  ACCESS_KEY: "Container Variable: ACCESS_KEY"
  CRON_SCHEDULE: 0 * * * *
  GCSOPTIONS: ""
  GCSPATH: gs://mybucket/
  SECRET_KEY: "Container Variable: SECRET_KEY"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/google-cloud-storage-backup
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  google-cloud-storage-backup:
    enabled: true
    mountPath: /data/backup
    readOnly: true
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
