env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/factorioservermanager
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /opt/factorio/config
  fsmmods:
    enabled: true
    mountPath: /opt/factorio/mods
  fsmsaves:
    enabled: true
    mountPath: /opt/factorio/saves
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  factorioport:
    enabled: true
    ports:
      factorioport:
        enabled: true
        port: 34197
        protocol: UDP
        targetPort: 34197
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8888
        protocol: HTTP
        targetPort: 80
