image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rdesktop
  tag: latest@sha256:745c6e3a02fcfe0380be039f690d48d1554fc9ea4cd3e5cc69f34cb1a749380d
ubuntuXFCEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-xfce
  tag: latest@sha256:eeba28bdf4514b66f744ed1204a4ca79c5d27277a32c98cb2e2541bdf483ecb5
  pullPolicy: Always
fedoraXFCEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-xfce
  tag: latest@sha256:b179c253db094543b2ab3973ae5d3582dc241cfdd7e2d856e7985b65295a64e0
  pullPolicy: Always
archXFCEImage:
  repository: tccr.io/truecharts/rdesktop-arch-xfce
  tag: latest@sha256:38df6aa57d268ab038e97dfc00b959e6b9c35ae280d1a886c59701d83abec662
  pullPolicy: Always

alpineKDEImage:
  repository: tccr.io/truecharts/rdesktop-alpine-kde
  tag: latest@sha256:c83a49f1ef3dfc4436daa56d0f4d21225bb84432b6511369d25388c5fb2fd198
  pullPolicy: Always
ubuntuKDEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-kde
  tag: latest@sha256:c71e0b8ce50b5223090509302415c6b8b9dfec784d661c3136c92abaf169b328
  pullPolicy: Always
fedoraKDEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-kde
  tag: latest@sha256:bbaff972d4775b8a58a923e37b69f48a908fd4df99a2888eaf9b084fbd3fb496
  pullPolicy: Always
archKDEImage:
  repository: tccr.io/truecharts/rdesktop-arch-kde
  tag: latest@sha256:1336ca1ebf1228d3d197fe222800c62310af0efffad7a80967198143a8b7a1f4
  pullPolicy: Always

alpineMATEImage:
  repository: tccr.io/truecharts/rdesktop-alpine-mate
  tag: latest@sha256:02797071d35ba9c791b4a36f0ee31909aa1d08781139ffc8a001e3cd3762417f
  pullPolicy: Always
ubuntuMATEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-mate
  tag: latest@sha256:e0383151b9f77d0a513cef73958301be2771ba857f48be1057a523f694df4a11
  pullPolicy: Always
fedoraMATEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-mate
  tag: latest@sha256:daf2959a2b8410a46ac921b55112438ccf3ec6681a3566cbc1029a1f13a74e7e
  pullPolicy: Always
archMATEImage:
  repository: tccr.io/truecharts/rdesktop-arch-mate
  tag: latest@sha256:af88441464c3f757900d9ac6445870e1ba62a0d9a7a6ca9e7dff16865af28dea
  pullPolicy: Always

alpineI3Image:
  repository: tccr.io/truecharts/rdesktop-alpine-i3
  tag: latest@sha256:7aa4d0c003690b3dd0e3bded9c2b6f62935198fdb71b95c6992a5faa34c6e007
  pullPolicy: Always
ubuntuI3Image:
  repository: tccr.io/truecharts/rdesktop-ubuntu-i3
  tag: latest@sha256:cfecf367f69ab01dc6c1b5f239e990a49bbe9b3883e7c916cc3f0f6e1998ddb9
  pullPolicy: Always
fedoraI3Image:
  repository: tccr.io/truecharts/rdesktop-fedora-i3
  tag: latest@sha256:c28b04136444a160e42723edea974e419ff8ab45d6ffc46ac025269a64ee55c2
  pullPolicy: Always
archI3Image:
  repository: tccr.io/truecharts/rdesktop-arch-i3
  tag: latest@sha256:1117b04eb269174a85f5aca07884cfd7bed035c04731fdf3a4a6e4a0eb44aca3
  pullPolicy: Always

alpineOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-alpine-openbox
  tag: latest@sha256:2636acc18d55d1ce5647829bacf2eaa2d203b87c1e295965f2725d6943e9dcb5
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-openbox
  tag: latest@sha256:44f56813827b45d7e51571fa1af7e3b394faa664f5bb613c5fec0a835a762fea
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-fedora-openbox
  tag: latest@sha256:63fc954ba3744acffc977a2fb60ade1547d40b62c77b49d46cfc3d80f5243d23
  pullPolicy: Always
archOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-arch-openbox
  tag: latest@sha256:c547829c2a2285290462729e2067ff0fa2b0696ae9bbfcdfb55e6b24b9caeecf
  pullPolicy: Always

alpineICEWMImage:
  repository: tccr.io/truecharts/rdesktop-alpine-icewm
  tag: latest@sha256:be33f29fd46fcbf2ab1b63dd982ab7b4880acf58823bae45ef684a6589ee71d3
  pullPolicy: Always
ubuntuICEWMImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-icewm
  tag: latest@sha256:c6fb91ca3ee3f0cc3b341ba47c55d3eeab1b58f942cc4d8596639fc8b2de3059
  pullPolicy: Always
fedoraICEWMImage:
  repository: tccr.io/truecharts/rdesktop-fedora-icewm
  tag: latest@sha256:2081fdd8ee70bc151b30d669ba1abc3bcf6f46c6419de48147b915c4547d74eb
  pullPolicy: Always
archICEWMImage:
  repository: tccr.io/truecharts/rdesktop-arch-icewm
  tag: latest@sha256:6136da8023bc512e8f8891bf560351a617900e2f44fb066014ac6f513b09a597
  pullPolicy: Always

imageSelector: image

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 3389
        protocol: HTTP
        targetPort: 3389

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
