image:
  repository: tccr.io/truecharts/drawio
  tag: 20.7.2@sha256:504f7c92d3a232336fb344685c837f5d4b68b4604740b5c9cb1a28f8dce93aef
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080

portal:
  enabled: true
