env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pigallery2
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /app/data/config
  db:
    enabled: true
    mountPath: /app/data/db
  image:
    enabled: true
    mountPath: /app/data/images/
    readOnly: true
  tmp:
    enabled: true
    mountPath: /app/data/tmp
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 80
        protocol: TCP
        targetPort: 80
