env:
  BUNDLE_WITHOUT: ""
  DATABASE_ENCODING: utf8
  DATABASE_HOST: 10.0.0.10
  DATABASE_NAME: tracks
  DATABASE_PASSWORD: password
  DATABASE_PORT: "3306"
  DATABASE_TYPE: mysql2
  DATABASE_USERNAME: tracks
  RAILS_ENV: production
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tracks
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 3000
        protocol: TCP
        targetPort: 3000
