env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/hoobs
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  applicationpath:
    enabled: true
    mountPath: /hoobs
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  homebridgeport:
    enabled: true
    ports:
      homebridgeport:
        enabled: true
        port: 51826
        protocol: TCP
        targetPort: 51826
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8082
        protocol: HTTP
        targetPort: 80
