env:
  ARGS:
    -transparent -server -state state -orport 127.0.0.1:3333 -transports obfs4
    -bindaddr obfs4-0.0.0.0:2222 -logLevel DEBUG -enableLogging
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/shapeshifter-obfuscator
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /state
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 2222
        protocol: TCP
        targetPort: 2222
