env:
  MALOJA_DATA_DIRECTORY: /config
  MALOJA_HOST: 0.0.0.0
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/maloja
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 42010
        protocol: TCP
        targetPort: 42010
