env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pritunl
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  http:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
        protocol: TCP
        targetPort: 80
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 443
        protocol: HTTP
        targetPort: 443
  vpntcp:
    enabled: true
    ports:
      vpntcp:
        enabled: true
        port: 1194
        protocol: TCP
        targetPort: 1194
  vpnudp:
    enabled: true
    ports:
      vpnudp:
        enabled: true
        port: 1194
        protocol: UDP
        targetPort: 1194
