env:
  GAME_ID: "824360"
  GAME_PARAMS: ?MaxPlayers=10
  GAME_PARAMS_EXTRA:
    -QueryPort=27016 -Port=27015 -CubePort=27018 -NoBattlEye -nosteamclient
    -game -server -log
  MAP: CubeWorld_Light
  PASSWRD: ""
  SERVER_NAME: PIXARKDocker
  SRV_ADMIN_PWD: adminDocker
  SRV_PWD: Docker
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pixark
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  cubeport:
    enabled: true
    ports:
      cubeport:
        enabled: true
        port: 27018
        protocol: UDP
        targetPort: 27018
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 27015
        protocol: UDP
        targetPort: 27015
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 27016
        protocol: UDP
        targetPort: 27016
