image:
  repository: tccr.io/truecharts/tvheadend
  pullPolicy: IfNotPresent
  tag: latest@sha256:5f124c87a92487c6a1ae27689a4029312d45e09e2ae468cc2951bb1e3bafdf95

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# See https://github.com/linuxserver/docker-tvheadend#parameters
env:
  RUN_OPTS: ""

service:
  main:
    ports:
      main:
        port: 9981
        targetPort: 9981
  htsp:
    enabled: true
    ports:
      htsp:
        enabled: true
        port: 9982
        targetPort: 9982

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
