env:
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rdesktop
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
  pathvarrundocker-sock:
    enabled: true
    mountPath: /var/run/docker.sock
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 3389
        protocol: TCP
        targetPort: 3389
