env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/googlephotossync
  tag: latest@sha256:dea8ce7c0cf521e95676757f9e2f55a7837f26f5f8a564d14cd3a1cd22e24187
persistence:
  config:
    enabled: true
    mountPath: /config
  hostpath1:
    enabled: true
    mountPath: /storage
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  enabled: false
