env:
  GAME_ID: "405100"
  GAME_PARAMS: ;autosaveenabled 1;addadmin 76561197963117432
  GAME_PORT: "12871"
  PASSWRD: ""
  QUERY_PORT: "12881"
  SRV_MAXPLAYERS: "50"
  SRV_NAME: Hurtworld Docker
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/hurtworld
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 12871
        protocol: UDP
        targetPort: 12871
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 12881
        protocol: UDP
        targetPort: 12881
