image:
  repository: tccr.io/truecharts/alist
  pullPolicy: IfNotPresent
  tag: 3.5.0@sha256:781f0fbe4a571be6975dfea3b7cbccb2af88d5b1cd015c420ec8866a82b0027a

service:
  main:
    ports:
      main:
        targetPort: 5244
        port: 10167

persistence:
  data:
    enabled: true
    mountPath: "/opt/alist/data"

portal:
  enabled: true
