env:
  SCHEDULE: "3600"
  TOKEN: 1a2b3c4d5e6f71a2b3c4d5e6f71a2b3c4d5e6f7b
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/llalon-github-backup
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  backuplocation:
    enabled: true
    mountPath: /home/docker/backups
  config:
    enabled: true
    mountPath: /home/docker/github-backup/config/
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
