env:
  FLOOD_AUTH: ""
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/qflood
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  hostportfor808:
    enabled: true
    ports:
      hostportfor808:
        enabled: true
        port: 8080
        protocol: TCP
        targetPort: 8080
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 3000
        protocol: HTTP
        targetPort: 3000
