env:
  DNS_ADDRS: 8.8.8.8,8.8.4.4
  METHOD: chacha20-ietf-poly1305
  PASSWORD: ""
  TIMEOUT: "300"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/shadowsocks
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8388
        protocol: TCP
        targetPort: 8388
  portudp:
    enabled: true
    ports:
      portudp:
        enabled: true
        port: 8388
        protocol: UDP
        targetPort: 8388
