env:
  GAME_ID: "1963720"
  GAME_PARAMS: ""
  PASSWRD: ""
  USERNAME: ""
  VALIDATE: ""
  WORLD_INDEX: "0"
  WORLD_NAME: Core Keeper Docker
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/corekeeper
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
