env:
  ANNOUNCEMENT: ""
  MAX_SECRET_LENGTH: "3000"
  MESSAGES_CONFIRM_VIEW_SECRET_BUTTON: View Secret
  MESSAGES_CONFIRM_VIEW_SECRET_HEADER: View this secret?
  MESSAGES_ERROR_SECRET_TOO_LONG: Input length too long
  MESSAGES_SUBMIT_SECRET_BUTTON: Encrypt Message
  MESSAGES_SUBMIT_SECRET_HEADER: Create A Self-Destructing Message
  MESSAGES_SUBMIT_SECRET_SUBHEADER: ""
  MESSAGES_VIEW_CODE_HEADER: Self-Destructing URL
  MESSAGES_VIEW_CODE_SUBHEADER:
    Share this URL via email, chat, or another messaging
    service. It will self-destruct after being viewed once.
  MESSAGES_VIEW_SECRET_HEADER: This message has been destroyed
  PRUNE_ENABLED: "true"
  PRUNE_MAX_DAYS: "730"
  PRUNE_MIN_DAYS: "365"
  RETURN_FULL_URL: "true"
  SITE_TITLE: FlashPaper - Self-Destructing Message
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/flashpaper
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  data:
    enabled: true
    mountPath: /var/www/html/data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8544
        protocol: TCP
        targetPort: 80
