env:
  APACHE2_PORT: "980"
  DATA_PERM: "770"
  FORCE_UPDATE: "false"
  UMASK: "0000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/debian-apt-mirror
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /debian-mirror/config
  data:
    enabled: true
    mountPath: /debian-mirror/data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 980
        protocol: TCP
        targetPort: 980
