image:
  repository: tccr.io/truecharts/bazarr
  pullPolicy: IfNotPresent
  tag: 1.1.2@sha256:2f7b1389c3531e2d59fd2d36ef886561175121a65c907256947f535b4dab891c

service:
  main:
    ports:
      main:
        port: 6767
        targetPort: 6767

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
