image:
  repository: tccr.io/truecharts/bazarr
  pullPolicy: IfNotPresent
  tag: 1.1.4@sha256:9d97fe81f54926ff2e4c281e1af4e22d65f44c178b19b37bbd1ae33baa5f3476

service:
  main:
    ports:
      main:
        port: 6767
        targetPort: 6767

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
