image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: 0.20.2269@sha256:ea5e9128370e53e02ce12431eccf5c3d5af1b75db326584113a429fe53fe7f07

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    enabled: true
    ports:
      main:
        port: 9117
        targetPort: 9117
    portsList:
      - name: "extraport"
        enabled: true
        port: 9118
        targetPort: 9118

serviceList:
  - name: extraservice
    enabled: true
    portsList:
      - name: "extrasvcport"
        enabled: true
        port: 9119
        targetPort: 9119

env:
  {}
  # PUID: 1001

persistence:
  config:
    enabled: true
    mountPath: "/config"
    type: pvc
    accessMode: ReadWriteOnce
    size: "100Gi"
