env:
  DOCKER_HUB_PASSWORD: ""
  DOCKER_HUB_USERNAME: ""
  KASM_PORT: ""
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/kasm
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  pathopt:
    enabled: true
    mountPath: /opt
  pathprofiles:
    enabled: true
    mountPath: /profiles
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 3000
        protocol: HTTP
        targetPort: 3000
  port6333:
    enabled: true
    ports:
      port6333:
        enabled: true
        port: 6333
        protocol: TCP
        targetPort: 6333
