env:
  UMASK_SET: "0022"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/go-auto-yt
  tag: vstable@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /app/config
  mounteddownloadsfolder:
    enabled: true
    mountPath: /app/downloads
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 9000
        protocol: TCP
        targetPort: 8080
