env:
  GALAXY_NAME: AvorionDocker
  GAME_ID: "565060"
  GAME_PARAMS: ""
  PASSWRD: ""
  UMASK: "000"
  USERNAME: ""
  VALIDATE: ""
stdin: true
tty: true
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/avorion
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  hostport2:
    enabled: true
    ports:
      hostport2:
        enabled: true
        port: 27000
        protocol: UDP
        targetPort: 27000
  hostport3:
    enabled: true
    ports:
      hostport3:
        enabled: true
        port: 27003
        protocol: UDP
        targetPort: 27003
  hostport4:
    enabled: true
    ports:
      hostport4:
        enabled: true
        port: 27020
        protocol: UDP
        targetPort: 27020
  hostport5:
    enabled: true
    ports:
      hostport5:
        enabled: true
        port: 27021
        protocol: UDP
        targetPort: 27021
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 27000
        protocol: TCP
        targetPort: 27000
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
