env:
  NVIDIA_DRIVER_CAPABILITIES: all
  NVIDIA_VISIBLE_DEVICES: ""
  VNC_PASSWD: "123456"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/obs-ndi
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  configpath:
    enabled: true
    mountPath: /config/obs-studio
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 5901
        protocol: TCP
        targetPort: 5901
