env:
  BASIC_URL: https://dl.xonotic.org/
  GAME_PARAMS: ""
  GAME_VERSION: 0.8.2
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/xonotic
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 26000
        protocol: UDP
        targetPort: 26000
