env:
  PS_LOG_LEVEL: ""
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/photostructure
  tag: vstable@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /ps/config
  library:
    enabled: true
    mountPath: /ps/library
  logs:
    enabled: true
    mountPath: /ps/logs
  tempscratchdisk:
    enabled: true
    mountPath: /ps/tmp
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 1787
        protocol: TCP
        targetPort: 1787
