env:
  DATA_PERM: "770"
  GAME_ID: "739590"
  GAME_PARAMS: ""
  PASSWRD: ""
  UMASK: "000"
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/eco
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 3001
        protocol: HTTP
        targetPort: 3001
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 3000
        protocol: UDP
        targetPort: 3000
