env:
  ALLOWED_TYPES: jpg,png,jpeg,bmp,gif
  ENABLE_AVIF: "false"
  QUALITY: "80"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/webp-server
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  storagecache:
    enabled: true
    mountPath: /opt/exhaust
  storagepics:
    enabled: true
    mountPath: /opt/pics
    readOnly: true
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 3333
        protocol: TCP
        targetPort: 3333
