env:
  ALLOWED_TYPES: jpg,png,jpeg,bmp,gif
  ENABLE_AVIF: "false"
  QUALITY: "80"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/webp-server
  tag: latest@sha256:5f4b3338957e6493fd49eeec34166c756a55e55ccbdb54971e47540de46b8532
persistence:
  storagecache:
    enabled: true
    mountPath: /opt/exhaust
  storagepics:
    enabled: true
    mountPath: /opt/pics
    readOnly: true
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3333
        protocol: TCP
        targetPort: 3333

portal:
  enabled: true
