image:
  repository: tccr.io/truecharts/satisfactory
  pullPolicy: IfNotPresent
  tag: 1.3.4@sha256:3f759fc098ae2b3f47e0dc36a64ff6ed829c2ff63ac99c47419b8d65083690a1

env:
  AUTOPAUSE: true
  AUTOSAVEINTERVAL: 300
  AUTOSAVENUM: 3
  AUTOSAVEONDISCONNECT: true
  CRASHREPORT: true
  DEBUG: false
  DISABLESEASONALEVENTS: false
  MAXPLAYERS: 4
  SERVERBEACONPORT: "{{ .Values.service.beacon.ports.beacon.targetPort }}"
  SERVERGAMEPORT: "{{ .Values.service.main.ports.main.targetPort }}"
  SERVERIP: "0.0.0.0"
  SERVERQUERYPORT: "{{ .Values.service.query.ports.query.targetPort }}"
  SKIPUPDATE: false
  STEAMBETA: false

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

persistence:
  config:
    enabled: true
    mountPath: "/config"

service:
  main:
    ports:
      main:
        targetPort: 7777
        port: 7777
        protocol: UDP
  beacon:
    enabled: true
    ports:
      beacon:
        enabled: true
        port: 15000
        targetPort: 15000
        protocol: UDP
  query:
    enabled: true
    ports:
      query:
        enabled: true
        port: 15777
        targetPort: 15777
        protocol: UDP

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

portal:
  enabled: false
