env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/universal-media-server
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /root/.config/UMS/
  media:
    enabled: true
    mountPath: /media
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 9001
        protocol: HTTP
        targetPort: 9001
  port1044:
    enabled: true
    ports:
      port1044:
        enabled: true
        port: 1044
        protocol: TCP
        targetPort: 1044
  port5002:
    enabled: true
    ports:
      port5002:
        enabled: true
        port: 5002
        protocol: TCP
        targetPort: 5002
