env:
  GAME_ID: "232290"
  GAME_NAME: dod
  GAME_PARAMS: -secure +maxplayers 24 +map dod_kalt
  GAME_PORT: "27015"
  PASSWRD: ""
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/dayofdefeatsource
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
  readiness:
    port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
  startup:
    port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 27015
        protocol: UDP
        targetPort: 27015
  tcprcon:
    enabled: true
    ports:
      tcprcon:
        enabled: true
        port: 27015
        protocol: TCP
        targetPort: 27015
