env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/glauth
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /app/config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  ldapport:
    enabled: true
    ports:
      ldapport:
        enabled: true
        port: 389
        protocol: TCP
        targetPort: 389
  ldapsport:
    enabled: true
    ports:
      ldapsport:
        enabled: true
        port: 636
        protocol: TCP
        targetPort: 636
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 5555
        protocol: HTTP
        targetPort: 5555
