env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/yacy
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  appdata:
    enabled: true
    mountPath: /opt/yacy_search_server/DATA
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 8443
        protocol: TCP
        targetPort: 8443
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8090
        protocol: HTTP
        targetPort: 8090
