image:
  repository: tccr.io/truecharts/emby
  pullPolicy: IfNotPresent
  tag: 4.7.10.0@sha256:3eb7884c5d26158f83c4aac006f53a6512cd2f85fe8ccafa523882c5b4a24f16

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 10079
        targetPort: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
