env:
  UMASK: "002"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/fmd2-wine
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  appluamodulespath:
    enabled: true
    mountPath: /app/FMD2/lua
  appuserdata:
    enabled: true
    mountPath: /app/FMD2/userdata
  appwineconfig:
    enabled: true
    mountPath: /config/.wine
  data:
    enabled: true
    mountPath: /app/FMD2/data
  downloaddirectory:
    enabled: true
    mountPath: /downloads
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 6080
        protocol: TCP
        targetPort: 6080
