image:
  repository: tccr.io/truecharts/cyberchef
  tag: 9.49.0@sha256:d16767d1c0b34816ef8f215f80e317e3cb98a537b8889307f514f2c549bd2eb5
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10219
        targetPort: 8000

portal:
  enabled: true
