env:
  WEBUI_PWD: admin
  WEBUI_TEMPLATE: default
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/amule
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  storagecomplete:
    enabled: true
    mountPath: /incoming
  storageconfig:
    enabled: true
    mountPath: /home/amule/.aMule
  storageincomplete:
    enabled: true
    mountPath: /temp
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 4711
        protocol: HTTP
        targetPort: 4711
  porttcp:
    enabled: true
    ports:
      porttcp:
        enabled: true
        port: 4662
        protocol: TCP
        targetPort: 4662
  portudp:
    enabled: true
    ports:
      portudp:
        enabled: true
        port: 4672
        protocol: UDP
        targetPort: 4672
