env:
  APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: "1"
  WINEARCH: win64
  WINEDEBUG: -all
  WINEPREFIX: /root/server
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/spaceengineers
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  savegame:
    enabled: true
    mountPath: /appdata/space-engineers/instances/Saves/
  serverconfig:
    enabled: true
    mountPath: /appdata/space-engineers/instances
  serverfiles:
    enabled: true
    mountPath: /appdata/space-engineers/SpaceEngineersDedicated
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 27017
        protocol: UDP
        targetPort: 27017
