# Default values for Jackett.

image:
  repository: deepquestai/deepstack
  pullPolicy: IfNotPresent
  tag: cpu-2021.02.1

strategy:
  type: Recreate

service:
  main:
    enabled: true
    ports:
      main:
        port: 5000

envTpl:
  # Permissions Settings
  USER_ID: "568"
  GROUP_ID: "568"

env:
  # TZ: UTC
  VISION-FACE: "True"
  VISION-DETECTION: "True"
  VISION-SCENE: "True"
  MODELSTORE-DETECTION: "/modelstore/detection"     # Path to custom models (needs to be on documentation)
  MODE: "High"    # High|Medium|Low

persistence:
  config:
    enabled: true
    mountPath: "/datastore"
    emptyDir:
      enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
