image:
  repository: tccr.io/truecharts/jenkins
  pullPolicy: IfNotPresent
  tag: 2.384.0@sha256:8c2398864143f4869c1ee82e12afb0a3ce6ce6443c032067a73a0cf4aa646d2a

podSecurityContext:
  runAsGroup: 1000
  runAsUser: 1000
  fsGroup: 1000

# securityContext:
#   readOnlyRootFilesystem: false

jenkins:
  java_opts: []
  jenkins_opts: []
  jenkins_java_opts: []
  plugins_force_upgrade: false
  upgrade_if_no_marker: false

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-secret'

probes:
  liveness:
    type: HTTP
    path: /login
  readiness:
    type: HTTP
    path: /login
  startup:
    type: HTTP
    path: /login

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 10280
  agent:
    enabled: true
    ports:
      agent:
        enabled: true
        port: 50000

persistence:
  data:
    enabled: true
    mountPath: /var/jenkins_home

portal:
  enabled: true
