env:
  DDNSR53_CREDENTIALS_ACCESSKEYID: ABCDEFGHIJKLMNO123456
  DDNSR53_CREDENTIALS_SECRETACCESSKEY: abcdefgh123456IJKLMN+OPQRS7890+ABCDEFGH
  DDNSR53_ROUTE53_HOSTEDZONEID: ABCEEFG123456789
  DDNSR53_ROUTE53_RECORDSSET_0_NAME: ddns.example.com.
  DDNSR53_ROUTE53_RECORDSSET_0_TTL: "300"
  DDNSR53_ROUTE53_RECORDSSET_0_TYPE: A
  LOG_JSON: "false"
  LOG_LEVEL: info
  MAX_RETRIES: "3"
  SCHEDULE: "*/30 * * * *"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ddns-route53
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
