image:
  repository: tccr.io/truecharts/dokuwiki
  pullPolicy: IfNotPresent
  tag: 20220731.1.0@sha256:fdb3c42c6619ea82d0719a482e85311ac2d90bd934ccf3e10acc59c683c7f88b

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  DOKUWIKI_USERNAME: "admin"
  DOKUWIKI_PASSWORD: "supersecret"
  DOKUWIKI_FULL_NAME: "Super Admin"
  DOKUWIKI_EMAIL: "admin@example.com"
  DOKUWIKI_WIKI_NAME: "DokuWiki"

service:
  main:
    ports:
      main:
        port: 10123
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/bitnami/dokuwiki"

portal:
  enabled: true
