env:
  AUTH_METHOD: puredb
  PASSIVE_PORT_RANGE: 30000:30009
  SECURE_MODE: "true"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pure-ftpd
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  data:
    enabled: true
    mountPath: /data
  ftpfolder:
    enabled: true
    mountPath: /home
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 2100
        protocol: HTTP
        targetPort: 2100
  pasvportrange:
    enabled: true
    ports:
      pasvportrange:
        enabled: true
        port: 30000
        protocol: TCP
        targetPort: 30000
