env:
  DATABASE_CONNECTION: ""
  HTTP_PASS: ""
  HTTP_USER: ""
  TUBESYNC_DEBUG: "False"
  TUBESYNC_HOSTS: ""
  TUBESYNC_WORKERS: "2"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tubesync
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 4848
        protocol: TCP
        targetPort: 4848
