env:
  GAME_ID: "1169370"
  GAME_PARAMS: ""
  WORLD_NAME: World
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/necesse
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 9023
        protocol: HTTP
        targetPort: 8080
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 14159
        protocol: UDP
        targetPort: 14159
