image:
  repository: tccr.io/truecharts/nitter
  pullPolicy: IfNotPresent
  tag: latest@sha256:1ccd5f6123333870afca1b3ca5267357cd57d45824ae47976023a01fb79c9334

nitter:
  general:
    title: nitter
    hostname: localhost:10606
    httpMaxConnections: 100
  cache:
    listMinutes: 240
    rssMinutes: 10
  config:
    base64Media: false
    enableRSS: true
    enableDebug: false
    proxy: ""
    proxyAuth: ""
    tokenCount: 10
  preferences:
    theme: Nitter
    replaceTwitter: nitter.net
    replaceYouTube: piped.video
    replaceReddit: teddit.net
    replaceInstagram: ""
    proxyVideos: true
    hlsPlayback: false
    infiniteScroll: false

probes:
  liveness:
    type: HTTP
    path: /
  readiness:
    type: HTTP
    path: /
  startup:
    type: HTTP
    path: /

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 10606

persistence:
  nitter-conf:
    enabled: true
    mountPath: /src/nitter.conf
    type: secret
    objectName: '{{ template "tc.common.names.fullname" . }}-nitter-secret'
    subPath: nitter.conf

redis:
  enabled: true
  existingSecret: rediscreds

portal:
  enabled: true
