env:
  BEASTHOST: <BEASTHOST>
  LAT: xx.xxxxx
  LONG: xx.xxxxx
  MLATHOST: <MLATHOST>
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tar1090
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8078
        protocol: TCP
        targetPort: 80
