image:
  repository: tccr.io/truecharts/audiobookshelf
  tag: 2.2.10@sha256:7e2c094a845e7ca21d066c8dd53594f43f0f10ca914a5ce8273396bbd3da0197
  pullPolicy: IfNotPresent

env:
  AUDIOBOOKSHELF_UID: "{{ .Values.security.PUID }}"
  AUDIOBOOKSHELF_GID: "{{ .Values.podSecurityContext.fsGroup }}"
  PORT: "{{ .Values.service.main.ports.main.port }}"
  TOKEN_SECRET:
    secretKeyRef:
      name: audiobookshelf-secrets
      key: TOKEN_SECRET

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 10223

probes:
  liveness:
    path: "/ping"
  readiness:
    path: "/ping"
  startup:
    path: "/ping"

persistence:
  config:
    enabled: true
    mountPath: "/config"
  audiobooks:
    enabled: true
    mountPath: "/audiobooks"
  metadata:
    enabled: true
    mountPath: "/metadata"

portal:
  enabled: true
