{{ range $index, $middlewareData := .Values.middlewares.rateLimit }}

---
# Declaring the user list
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $middlewareData.name }}
  namespace: {{ if or ( not .Values.ingressClass.enabled ) ( and ( .Values.ingressClass.enabled ) ( .Values.ingressClass.isDefaultClass ) ) }}traefikmiddlewares{{ else }}ix-{{ .Release.Name }}{{ end }}
spec:
  rateLimit:
    average: {{ $middlewareData.average }}
    burst: {{ $middlewareData.burst }}
{{ end }}
