env:
  VNC_PW: vncpassword
  VNC_RESOLUTION: 1280x1024
  VNC_VIEW_ONLY: "false"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/bitcoinwalletgui
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  bitcoinblockchainpath:
    enabled: true
    mountPath: /headless/.bitcoin/
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 6901
        protocol: HTTP
        targetPort: 6901
  vncport:
    enabled: true
    ports:
      vncport:
        enabled: true
        port: 5905
        protocol: TCP
        targetPort: 5901
