env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/filestash
  tag: latest@sha256:7b6e0ceeceea44b6e08c97aba5f31890cc3494b823a8d7a2b116ff7a42218279
persistence:
  appdata:
    enabled: true
    mountPath: /app/data/state/
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8334
        protocol: TCP
        targetPort: 8334

portal:
  enabled: true
