image:
  repository: tccr.io/truecharts/mylar3
  tag: 0.6.9@sha256:cbf7d5021d19b41220d4d6f96fd5e74b288904e469072f5bfae8d2655d8c010c
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
