env:
  GAME_ID: "489650 "
  GAME_PARAMS: ""
  PASSWRD: ""
  UMASK: "000"
  USERNAME: ""
  VALIDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/citadel-forgedwithfire
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 7777
        protocol: UDP
        targetPort: 7777
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 27015
        protocol: UDP
        targetPort: 27015
