image:
  repository: tccr.io/truecharts/cloudflared
  pullPolicy: IfNotPresent
  tag: 2022.12.0@sha256:be7f9f8117ad4e3fdb1a1ec9e9d58bd51433c6ce55d9f9af6bdb4b601d851386

extraArgs:
  - tunnel
  - --no-autoupdate
  - run
  - --token
  - "{{ .Values.cloudflared.token }}"

cloudflared:
  token: ""

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

portal:
  enabled: false
