env:
  MAGNETICOD_ADDRESS: 0.0.0.0
  MAGNETICOD_INTERVAL: "1"
  MAGNETICOD_LEECHES: "50"
  MAGNETICOD_NEIGHBORS: "1000"
  MAGNETICOD_PORT: "0"
  MAGNETICOD_VERBOSE: ""
  MAGNETICOW_ADDRESS: 0.0.0.0
  MAGNETICOW_PASSWORD: magnetico
  MAGNETICOW_USERNAME: magnetico
  MAGNETICOW_VERBOSE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/magnetico-environment
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  databaselocation:
    enabled: true
    mountPath: /root/.local/share/magneticod
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8556
        protocol: TCP
        targetPort: 8080
