env:
  RS_PASSWORD: Password
  RS_USERNAME: admin
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/restreamer
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  datapath:
    enabled: true
    mountPath: /restreamer/db
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8080
        protocol: TCP
        targetPort: 8080
