env:
  CUSTOM_RES_H: "768"
  CUSTOM_RES_W: "1280"
  FERDI_V: stable@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
  UMASK: "000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ferdi-client
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  datadir:
    enabled: true
    mountPath: /ferdi
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8080
        protocol: TCP
        targetPort: 8080
