image:
  repository: tccr.io/truecharts/pgadmin4
  pullPolicy: IfNotPresent
  tag: 6.20@sha256:10ccedac4c8a031841c309e1d2365ddd4e3f7c2d888b44f261cb181616db433b

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 5050

service:
  main:
    ports:
      main:
        port: 10024
        targetPort: 80

secretEnv:
  PGADMIN_DEFAULT_EMAIL: "replace@this.now"
  PGADMIN_DEFAULT_PASSWORD: "changeme"

persistence:
  config:
    enabled: true
    mountPath: "/var/lib/pgadmin"

portal:
  enabled: true
