image:
  repository: tccr.io/truecharts/homepage
  tag: 0.5.2@sha256:32f582496ab795578925b1da7a0ba77de4d1184bec9049ca0d3fba15915f7def
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 10352
        protocol: HTTP
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: /app/config

portal:
  enabled: true
