# Default values for Jackett.

image:
  repository: ghcr.io/truecharts/pihole
  pullPolicy: IfNotPresent
  tag: 2021.09@sha256:4653aee50cff8a679e03f2bcd1b05fc2f8b6614896c5554e081b08a3ce60a578

envFrom:
  - configMapRef:
      name: pihole-env

service:
  main:
    enabled: true
    ports:
      main:
        port: 80
  dns-tcp:
    enabled: true
    ports:
      https:
        enabled: true
        port: 53
  dns:
    enabled: true
    ports:
      dns:
        enabled: true
        port: 53

pihole:
  WEBPASSWORD: "somepassword"
  DNS1: "9.9.9.9"
  DNS2: "149.112.112.112"


persistence:
  config:
    enabled: true
    mountPath: "/etc/pihole"
    type: pvc
    accessMode: ReadWriteOnce
    size: "100Gi"
  dnsmasq:
    enabled: true
    mountPath: "/etc/dnsmasq.d"
    type: pvc
    accessMode: ReadWriteOnce
    size: "100Gi"
