env:
  EXILEMOD_SERVER_URL: http://www.exilemod.com/ExileServer-1.0.4a.zip
  GAME_ID: "233780"
  GAME_PARAMS: ""
  GAME_PORT: "2302"
  MARIA_DB_ROOT_PWD: ExileMod
  PASSWRD: ""
  USERNAME: ""
  VALIDATE: ""
  WORKSHOP_MAN_INST: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/arma3exilemod
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  profiles:
    enabled: true
    mountPath: /serverdata/.local/share
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 2302
        protocol: TCP
        targetPort: 2302
  tcpmariadb:
    enabled: true
    ports:
      tcpmariadb:
        enabled: true
        port: 3306
        protocol: TCP
        targetPort: 3306
  udpbattleyetra:
    enabled: true
    ports:
      udpbattleyetra:
        enabled: true
        port: 2306
        protocol: UDP
        targetPort: 2306
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 2302
        protocol: UDP
        targetPort: 2302
  udpsteammaster:
    enabled: true
    ports:
      udpsteammaster:
        enabled: true
        port: 2304
        protocol: UDP
        targetPort: 2304
  udpsteamquerry:
    enabled: true
    ports:
      udpsteamquerry:
        enabled: true
        port: 2303
        protocol: UDP
        targetPort: 2303
  udpvonport:
    enabled: true
    ports:
      udpvonport:
        enabled: true
        port: 2305
        protocol: UDP
        targetPort: 2305
