env:
  CONVERSION_FORMAT: mkv
  DELETE_TS: "1"
  NVIDIA_VISIBLE_DEVICES: ""
  POST_PROCESS: comchap
  SOURCE_EXT: ts
  SUBTITLES: "0"
  UMASK: "000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/post-recording
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  backupfolder:
    enabled: true
    mountPath: /backup
  config:
    enabled: true
    mountPath: /config
  watchfolder:
    enabled: true
    mountPath: /watch
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
