env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/dns-doh-companion
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  dnsudp:
    enabled: true
    ports:
      dnsudp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 53
        protocol: TCP
        targetPort: 53
