env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/filegator
  tag: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
  storageconfigfile:
    enabled: true
    mountPath: /var/www/localhost/filegator/configuration.php
    readOnly: true
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8048
        protocol: HTTP
        targetPort: 80
  webuihttps:
    enabled: true
    ports:
      webuihttps:
        enabled: true
        port: 8049
        protocol: TCP
        targetPort: 443
