name: "Prune Old Releases"

on:
  workflow_dispatch:

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    name: "prune old releases"
    steps:
    - name: prune
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 200
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
