image:
  repository: tccr.io/truecharts/prowlarr
  tag: 1.1.3.2521@sha256:6a4463b8a9488c3b21a2b382e9f57d009e8ef529960f434967c48f968f0326f8
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 9696
        targetPort: 9696

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
