image:
  repository: tccr.io/truecharts/prowlarr
  tag: 0.4.9.2083@sha256:5bf1fe7838e5cf249aa597c46999336fcac9a3019760a4761619d6d7d1353456
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 9696
        targetPort: 9696

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
