braveImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: brave@sha256:5d853c22f1a1f47a44f8477b5acaa0fb8a0e81e04d333ce702ae88ea922d4fb0
chromeImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: google-chrome@sha256:abdedb3d37fd93fb7cfb3670cc44921b8f93eac2f5a9ae4df19f3e7b70ce0fb9
chromiumImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: chromium@sha256:b650898fe4504321bf49bb74fb7cffe090604e564b939967e2bbe3c2358591b4
edgeImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: microsoft-edge@sha256:cfebc5fd0ba19d0204360e79fb8f7e330d5d00c970f91108e89843aac336d9e8
image:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: firefox@sha256:5c2d1c0c0ebd23afd1b23bb99d86ad1707bdcdb78df9e8f374cd5d6a81bcd1f5
imageSelector: image
portal:
  open:
    enabled: true
remminaImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: remmina@sha256:0c512621f6c2179e9bd011aa3bb99a66d551fca3041321fd2a6362f306526cfb
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10294
        protocol: http
        targetPort: 8080
  mux-tcp:
    enabled: true
    ports:
      mux-tcp:
        enabled: true
        port: 52100
        protocol: tcp
        targetPort: 52100
  mux-udp:
    enabled: true
    ports:
      mux-udp:
        enabled: true
        port: 52100
        protocol: udp
        targetPort: 52100
torImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: tor-browser@sha256:1cbd01b6d975d23c4dfc9caf5aa52936f313fc12d3b4f85c320194ea5553a29c
vivaldiImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: vivaldi@sha256:cfbee0000006c076d994dddd85c32faf16135165a2a0cfdecbc4de7dc6b94df6
vlcImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: vlc@sha256:1313b3c5e9d00a4cd30d17a523a81758f38d22e84a6790ab6d0de367c1134cc6
vncviewerImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: vncviewer@sha256:d6e961e5b15fc58639ac6b4eeb791c5b48c859e69d65d25c20ff92bf7c95b458
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NEKO_CONTROL_PROTECTION: "false"
            NEKO_IMPLICIT_CONTROL: "false"
            NEKO_IPFETCH: ""
            NEKO_LOCKS: ""
            NEKO_NAT1TO1: ""
            NEKO_PASSWORD: userpass
            NEKO_PASSWORD_ADMIN: adminpass
            NEKO_PROXY: "true"
            NEKO_SCREEN: 1920x1080@30
            NEKO_tcpMUX: "52100"
            NEKO_udpMUX: "52100"
xfceImage:
  pullPolicy: IfNotPresent
  repository: m1k1o/neko
  tag: xfce@sha256:df36f438915ac4f1ffa18608e7d9169e330cea4f6c3f91d3d6257031c9cbc0eb
