# Default values for Calibre-Web.

image:
  repository: linuxserver/calibre-web
  pullPolicy: IfNotPresent
  tag: version-0.6.11

strategy:
  type: Recreate

# Configure the Security Context for the Pod
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

service:
  main:
    ports:
      main:
        port: 8083

env: {}
  # TZ:
  # PUID:
  # PGID:
  # UMASK:
  # DOCKER_MODS:

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir:
      enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
